name: scalatest-maven-plugin

on: [push, pull_request]

jobs:
  verify:

    runs-on: ubuntu-latest

    steps:
      - name: git
        uses: actions/checkout@v4

      - name: java
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: maven
        run: mvn -B clean verify --file pom.xml
