name: scalatest-maven-plugin

on: [push]

jobs:
  verify:

    runs-on: ubuntu-latest

    steps:
      - name: git
        uses: actions/checkout@v2

      - name: java
        uses: actions/setup-java@v1.4.2
        with:
          java-version: '8'

      - name: maven
        run: mvn -B clean verify --file pom.xml
